// Copyright (c) 2026 jzw
// SPDX-License-Identifier: Apache-2.0
//
// rclcpp_components 共享库符号可见性（对齐 video_camera / rtsp2）

#ifndef APRILTAG_LOCALIZATION_VISIBILITY_CONTROL_HPP_
#define APRILTAG_LOCALIZATION_VISIBILITY_CONTROL_HPP_

#ifdef __cplusplus
extern "C" {
#endif

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define APRILTAG_LOCALIZATION_COMPONENTS_EXPORT __attribute__((dllexport))
#define APRILTAG_LOCALIZATION_COMPONENTS_IMPORT __attribute__((dllimport))
#else
#define APRILTAG_LOCALIZATION_COMPONENTS_EXPORT __declspec(dllexport)
#define APRILTAG_LOCALIZATION_COMPONENTS_IMPORT __declspec(dllimport)
#endif
#ifdef APRILTAG_LOCALIZATION_COMPONENTS_BUILDING_DLL
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC APRILTAG_LOCALIZATION_COMPONENTS_EXPORT
#else
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC APRILTAG_LOCALIZATION_COMPONENTS_IMPORT
#endif
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC_TYPE APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC
#define APRILTAG_LOCALIZATION_COMPONENTS_LOCAL
#else
#define APRILTAG_LOCALIZATION_COMPONENTS_EXPORT __attribute__((visibility("default")))
#define APRILTAG_LOCALIZATION_COMPONENTS_IMPORT
#if __GNUC__ >= 4
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC __attribute__((visibility("default")))
#define APRILTAG_LOCALIZATION_COMPONENTS_LOCAL __attribute__((visibility("hidden")))
#else
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC
#define APRILTAG_LOCALIZATION_COMPONENTS_LOCAL
#endif
#define APRILTAG_LOCALIZATION_COMPONENTS_PUBLIC_TYPE
#endif

#ifdef __cplusplus
}
#endif

#endif  // APRILTAG_LOCALIZATION_VISIBILITY_CONTROL_HPP_
